### ISSUE TITLE
Please change the name to something less generic and add a screen shot

### ISSUE THREAD

**Issue by unixorn** [aprilnops/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them. Also, zsh-theme is a bit generic, please give it something descriptive so I can add it to the themes list.

Thanks!

**Comment by aprilnops** [comment]
@unixorn ok,fix it.  tks!
